site_name: Blogs
site_url: !ENV [SITE_URL, 'http://localhost:8000']
repo_url: https://github.com/yunline/blogs

docs_dir: content

theme: 
  name: material
  custom_dir: overrides

  features:
    # 支持一键复制代码
    - content.code.copy

    # 支撑toc跟随滚动
    - toc.follow

    # 配置导航栏
    - navigation.tabs
    - navigation.expand
  
plugins:
  # 支持导航栏自定义与自动化
  # （太酷了这个插件）
  - awesome-nav
  
extra_javascript:
  # 支持latex公式
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-chtml.min.js

  # 支持博客头部信息（标签和发布日期）
  - inject_blog_header/inject_post_header.js

extra_css:
  # 支持博客头部信息
  - inject_blog_header/inject_post_header.css

# 监听overrides文件夹变化
# （主要方便debug）
watch:
  - overrides

markdown_extensions:
  # 支持在html标签里写markdown
  # （需要在html标签里添加 markdown="1"属性）
  - markdown.extensions.md_in_html

  # 支持删除线
  - pymdownx.tilde 

  # 支持latex公式
  - pymdownx.arithmatex: 
      generic: true
  
  # 支持代码高亮
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.superfences:
      # 支持mermaid导图
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # 支持内嵌emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg